# Generated by Django 6.0.3 on 2026-03-23 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('borrow_request', 'Borrow Request'), ('request_accepted', 'Request Accepted'), ('request_rejected', 'Request Rejected'), ('book_returned', 'Book Returned'), ('extension_request', 'Extension Request'), ('extension_accepted', 'Extension Accepted'), ('review_received', 'Review Received')], max_length=40)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=260, null=True)),
                ('is_read', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
