# Generated by Django 6.0.3 on 2026-04-11 05:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_images/default_profile', max_length=255, null=True, verbose_name='image'),
        ),
    ]
