# Generated by Django 6.0.3 on 2026-03-09 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, default='book_cover/default_cover.png', null=True, upload_to='book_cover/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category')),
                ('tags', models.ManyToManyField(related_name='book_list', to='books.tag')),
            ],
        ),
    ]
