# Generated by Django 6.0.3 on 2026-04-11 05:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='book_cover/default_cover', max_length=255, null=True, verbose_name='image'),
        ),
    ]
