# Generated by Django 6.0.3 on 2026-03-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_borrowrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
